CREATE TABLE USERS (
    CREATED_TMS    TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    UPD_UID        CHAR(20) NOT NULL,
    UPDATED_TMS    TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    USER_ID        CHAR(20)  NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    RESET_PASS_FLG CHAR(1)   NOT NULL DEFAULT 'Y',
    USER_LEVEL     INT NOT NULL,
    PRIMARY KEY (USER_ID)
);