CREATE TABLE ATTENDANCE (
    CREATED_TMS    TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    UPD_UID        CHAR(20) NOT NULL,
    UPDATED_TMS    TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    USER_ID        	CHAR(20)  NOT NULL,
    ATTENDANCE_DATE	DATE         NOT NULL,
    START_ATTEND_TMS    TIMESTAMP(3) NOT NULL,
    END_ATTEND_TMS      TIMESTAMP(3) NULL,
    CHECK_IN_IMG VARCHAR(500) NOT NULL,
    CHECK_OUT_IMG VARCHAR(500) NULL,
    PRIMARY KEY (USER_ID, ATTENDANCE_DATE),
    INDEX idx_attendance_date (ATTENDANCE_DATE)
);